apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cpa-rest
  name: cpa-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpa-rest
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cpa-rest
    spec:
      containers:
      containers:
      - name: cpa-rest
        image: chouhan/cpa-rest:latest
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cpa-rest-service
  name: cpa-rest-service
spec:
  ports:
  - name: cpa-rest-service-port
    port: 9099
    protocol: TCP
    targetPort: 9099
  selector:
    app: cpa-rest
  type: ClusterIP
status:
  loadBalancer: {}
